# Generated by Django 4.2.16 on 2026-05-10 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seasons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название сезона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='SeasonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, validators=[seasons.models.validate_positive_points], verbose_name='Очки')),
                ('last_action', models.CharField(blank=True, max_length=120, verbose_name='Последнее действие')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='seasons.season', verbose_name='Сезон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат сезона',
                'verbose_name_plural': 'Результаты сезона',
                'ordering': ('-points', 'updated_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('title', 'start_date'), name='unique_season_title_start_date'),
        ),
        migrations.AddConstraint(
            model_name='seasonresult',
            constraint=models.UniqueConstraint(fields=('season', 'user'), name='unique_result_for_season_user'),
        ),
    ]
